#ifndef DEBUGGING_H
#define DEBUGGING_H

#ifdef DEBUG
#define DEBUG_ERROR(FUNCNAME) printf("%s ERROR\n", FUNCNAME);
#define DEBUG_SERROR(FUNCNAME, MESSAGE, ERROR) printf("%s %s ERROR: %s\n", FUNCNAME, MESSAGE, ERROR);
#define DEBUG_HERROR(FUNCNAME, MESSAGE, ERROR) printf("%s %s ERROR: 0x%x\n", FUNCNAME, MESSAGE, ERROR);
#define DEBUG_LHERROR(FUNCNAME, MESSAGE, ERROR) printf("%s %s ERROR: 0x%p\n", FUNCNAME, MESSAGE, ERROR);
#define DEBUG_DERROR(FUNCNAME, MESSAGE, ERROR) printf("%s %s ERROR: %d\n", FUNCNAME, MESSAGE, ERROR);
#define DEBUG_INFO(MESSAGE, ...) printf( MESSAGE "\n", __VA_ARGS__);
#else 
#define DEBUG_ERROR(FUNCNAME)
#define DEBUG_SERROR(FUNCNAME, MESSAGE, ERROR)
#define DEBUG_HERROR(FUNCNAME, MESSAGE, ERROR)
#define DEBUG_LHERROR(FUNCNAME, MESSAGE, ERROR)
#define DEBUG_DERROR(FUNCNAME, MESSAGE, ERROR)

#define DEBUG_INFO(MESSAGE, ...)
#endif

#endif
